(load "main.scm")

(define dim 2)

(define (make-gamma d S)
  (let*
      ((beta (new-gsl-vector 2))
       (mu (vector (new-gsl-vector dim) (new-gsl-vector dim)))
       (Sigma (vector (new-gsl-matrix dim dim) (new-gsl-matrix dim dim))))
    (gsl-vector-set-all beta 0.5)
    (gsl-vector-set-all (vector-ref mu 0) (* -1.0 d))
    (gsl-matrix-set-identity (vector-ref Sigma 0))
    (gsl-vector-set-all (vector-ref mu 1) d)
    (gsl-matrix-set-identity (vector-ref Sigma 1))
    (gsl-matrix-scale (vector-ref Sigma 1) S)
    (new-mcmclib-raptor-gamma beta (va2ca mu) (ma2ca Sigma))))
(define (alpha-star d S)
  (mcmclib-raptor-alpha-star-fun (make-gamma d S)))

(define bah (make-gamma 1 2))
(define bb (mcmclib-raptor-gamma-beta-hat-get bah))
(define mm (mcmclib-raptor-gamma-mu-hat-get bah))
(gv2v (vectorArray-getitem mm 0))
(gv2v (vectorArray-getitem mm 1))
(define ss (mcmclib-raptor-gamma-Sigma-hat-get bah))
(M2ll (matrixArray-getitem ss 0))
(M2ll (matrixArray-getitem ss 1))
(mcmclib-raptor-alpha-star-fun bah)
(alpha-star 1 2)
