(load "main.scm")

(define dim 2)

(define (make-gamma d S)
  (let*
      ((beta (make-filled-vector 0.5 2))
       (mu (vector (make-filled-vector (* -1.0 d) dim)
                   (make-filled-vector d dim)))
       (Sigma (vector (diag 1.0 dim)
                      (diag S dim))))
    (new-mcmclib-raptor-gamma beta mu Sigma)))
(define (alpha-star d S)
  (mcmclib-raptor-alpha-star-fun (make-gamma d S)))

(define bah (make-gamma 1 2))
(define bb (mcmclib-raptor-gamma-beta-hat-get bah))
(define mm (mcmclib-raptor-gamma-mu-hat-get bah))
(gv2v (vectorArray-getitem mm 0))
(gv2v (vectorArray-getitem mm 1))
(define ss (mcmclib-raptor-gamma-Sigma-hat-get bah))
(gM2M (matrixArray-getitem ss 0))
(gM2M (matrixArray-getitem ss 1))
(mcmclib-raptor-alpha-star-fun bah)
(alpha-star 1 2)
